Update ug sg
AY2021S1-CS2103T-T17-2/tp pull request #101
Opened 2020-10-26 05:46 UTC by sgn00

2020-10-26 11:56 UTC, moyj01 requested changes
Some inputs from me. Please take a look and make the appropriate changes accordingly.

2020-10-26 11:56 UTC, moyj01 commented on docs/UserGuide.md
> +Review the current list of flashcards. This puts the user in review mode and the user can no
Maybe you can consider using "Reviews" instead of "Review" so that our UG has a standardised format.

2020-10-26 11:56 UTC, moyj01 commented on docs/UserGuide.md
> +<div markdown="span" class="alert alert-primary">:memo: Note: The review and success frequency of a flashcard is only affected by quiz mode.
The review and success frequencies of a flashcard are only affected by quiz mode.

2020-10-27 04:19 UTC, tanzhuoyao-nus reviewed
Besides what Melvin stated, LGTM!

2020-10-27 04:57 UTC, merged