Update UG with quiz feature and update index.md
AY2021S1-CS2103T-T17-2/tp pull request #105
Opened 2020-10-26 12:39 UTC by moyj01

2020-10-26 15:45 UTC, tanzhuoyao-nus requested changes
Would be good if you can add your quiz feature into the command summary 👍

2020-10-27 04:56 UTC, sgn00 requested changes
Refer to comments

2020-10-27 04:56 UTC, sgn00 commented on docs/UserGuide.md
> +Upon pressing the down arrow key, the user will be prompted if they got the answer correct. The user can then press
would be good to use ↓ instead of down arrow key

2020-10-27 04:56 UTC, sgn00 commented on docs/UserGuide.md
> +* `y` to represent correct answer. This input will only be recognised after the `↓ key` is pressed
maybe should make it more clear that y/n is feedback not giving the answer

2020-10-27 05:52 UTC, merged